### PR TITLE
Modified Delimiter Functionality

### PR DESCRIPTION
**Pull request by NandVinchhi**
I changed the default delimiter to space (" "), since earlier the default value was "" and you had to type in a space for many functionalities such as changing case of sentence. Pls review thnx.

### CODE REVIEW

**Comment by soumitradev** [comment]
I actually did that on purpose, since it is sometimes useful to separate each character in a string. I want the parser to have as many options as possible. After this change, we will not be able to separate each character. If you can convince me to give up this functionality, I will merge this PR.

**Comment by NandVinchhi** [comment]
You can still do this. You just have to backspace the space in the input box. I simply changed the default to space as it is more commonly used.

**Comment by soumitradev** [comment]
Oh, I see now. I thought you changed the Javascript in the HTML. I'll merge this right now, sorry for being a dumbass.

**Comment by soumitradev** [comment]
Actually, I think a comma and space `a, b` would be better since most programming languages require lists and arrays to be that way.

**Review by soumitradev — APPROVED** [review]
If you think just space is better, we can still go with that.

**Comment by NandVinchhi** [comment]
k a comma and a space would be better ig. I'll update.

**Comment by NandVinchhi** [comment]
ya its already done

**Comment by soumitradev** [comment]
Sure, I'll merge now.

**Pull request merged**
